"""init database schema

Revision ID: 0cc8e6916a36
Revises: 
Create Date: 2025-11-02 10:44:21.117982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc8e6916a36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_authorities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_provider', 'git_authorities', ['user_id', 'provider'], unique=False)
    op.create_index(op.f('ix_git_authorities_user_id'), 'git_authorities', ['user_id'], unique=False)
    op.create_table('git_repositories',
    sa.Column('id', sa.String(), nullable=False, comment='ID'),
    sa.Column('user_id', sa.String(), nullable=False, comment='用户ID'),
    sa.Column('git_provider', sa.String(), nullable=False, comment='Git提供商'),
    sa.Column('repository_url', sa.String(), nullable=False, comment='仓库URL'),
    sa.Column('organization', sa.String(), nullable=False, comment='组织'),
    sa.Column('repository_name', sa.String(), nullable=False, comment='仓库名称'),
    sa.Column('branch', sa.String(), nullable=True, comment='分支'),
    sa.Column('description', sa.Text(), nullable=True, comment='仓库描述'),
    sa.Column('local_path', sa.String(), nullable=True, comment='本地路径'),
    sa.Column('is_cloned', sa.Boolean(), nullable=True, comment='是否已克隆'),
    sa.Column('last_sync_time', sa.DateTime(), nullable=True, comment='最后同步时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_git_repositories_id'), 'git_repositories', ['id'], unique=False)
    op.create_table('repo_wiki_content_sources',
    sa.Column('id', sa.String(), nullable=False, comment='ID'),
    sa.Column('content_id', sa.String(length=36), nullable=False, comment='内容ID'),
    sa.Column('source_path', sa.String(length=500), nullable=False, comment='源路径'),
    sa.Column('source_name', sa.String(length=200), nullable=False, comment='源名称'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_wiki_content_sources_id'), 'repo_wiki_content_sources', ['id'], unique=False)
    op.create_table('repo_wiki_documents',
    sa.Column('id', sa.String(), nullable=False, comment='ID'),
    sa.Column('repo_id', sa.String(), nullable=False, comment='代码仓对象库ID'),
    sa.Column('classify', sa.String(), nullable=True, comment='分类'),
    sa.Column('description', sa.Text(), nullable=True, comment='文档描述'),
    sa.Column('readme_content', sa.Text(), nullable=True, comment='README内容'),
    sa.Column('optimized_directory_struct', sa.Text(), nullable=True, comment='优化目录结构'),
    sa.Column('processing_status', sa.String(), nullable=True, comment='处理状态'),
    sa.Column('processing_progress', sa.Integer(), nullable=True, comment='处理进度'),
    sa.Column('processing_message', sa.Text(), nullable=True, comment='处理消息'),
    sa.Column('is_embedded', sa.Boolean(), nullable=True, comment='是否嵌入'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['git_repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_wiki_documents_id'), 'repo_wiki_documents', ['id'], unique=False)
    op.create_index(op.f('ix_repo_wiki_documents_repo_id'), 'repo_wiki_documents', ['repo_id'], unique=False)
    op.create_table('mini_maps',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='文档ID'),
    sa.Column('value', sa.Text(), nullable=False, comment='思维导图数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['repo_wiki_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mini_maps_id'), 'mini_maps', ['id'], unique=False)
    op.create_table('repo_wiki_catalogs',
    sa.Column('id', sa.String(), nullable=False, comment='ID'),
    sa.Column('document_id', sa.String(), nullable=False, comment='文档ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='目录名称'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='目录URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='目录描述'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='目录父级ID'),
    sa.Column('order', sa.Integer(), nullable=True, comment='当前目录排序'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='是否处理完成'),
    sa.Column('prompt', sa.Text(), nullable=True, comment='提示词'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['repo_wiki_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_wiki_catalogs_document_id'), 'repo_wiki_catalogs', ['document_id'], unique=False)
    op.create_index(op.f('ix_repo_wiki_catalogs_id'), 'repo_wiki_catalogs', ['id'], unique=False)
    op.create_table('repo_wiki_commit_records',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='文档ID'),
    sa.Column('commit_id', sa.String(length=100), nullable=False, comment='提交ID'),
    sa.Column('commit_message', sa.String(length=1000), nullable=False, comment='提交消息'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='作者'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['repo_wiki_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_wiki_commit_records_id'), 'repo_wiki_commit_records', ['id'], unique=False)
    op.create_table('repo_wiki_overviews',
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='文档ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['repo_wiki_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_wiki_overviews_id'), 'repo_wiki_overviews', ['id'], unique=False)
    op.create_table('repo_wiki_contents',
    sa.Column('id', sa.String(), nullable=False, comment='ID'),
    sa.Column('catalog_id', sa.String(length=36), nullable=False, comment='绑定的repowiki目录ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('content', sa.Text(), nullable=True, comment='文档实际内容'),
    sa.Column('size', sa.Integer(), nullable=True, comment='文档大小'),
    sa.Column('source_file_items', sa.JSON(), nullable=True, comment='相关源文件源数据，DocumentFileItemSource'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='源数据'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['repo_wiki_catalogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_wiki_contents_id'), 'repo_wiki_contents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_wiki_contents_id'), table_name='repo_wiki_contents')
    op.drop_table('repo_wiki_contents')
    op.drop_index(op.f('ix_repo_wiki_overviews_id'), table_name='repo_wiki_overviews')
    op.drop_table('repo_wiki_overviews')
    op.drop_index(op.f('ix_repo_wiki_commit_records_id'), table_name='repo_wiki_commit_records')
    op.drop_table('repo_wiki_commit_records')
    op.drop_index(op.f('ix_repo_wiki_catalogs_id'), table_name='repo_wiki_catalogs')
    op.drop_index(op.f('ix_repo_wiki_catalogs_document_id'), table_name='repo_wiki_catalogs')
    op.drop_table('repo_wiki_catalogs')
    op.drop_index(op.f('ix_mini_maps_id'), table_name='mini_maps')
    op.drop_table('mini_maps')
    op.drop_index(op.f('ix_repo_wiki_documents_repo_id'), table_name='repo_wiki_documents')
    op.drop_index(op.f('ix_repo_wiki_documents_id'), table_name='repo_wiki_documents')
    op.drop_table('repo_wiki_documents')
    op.drop_index(op.f('ix_repo_wiki_content_sources_id'), table_name='repo_wiki_content_sources')
    op.drop_table('repo_wiki_content_sources')
    op.drop_index(op.f('ix_git_repositories_id'), table_name='git_repositories')
    op.drop_table('git_repositories')
    op.drop_index(op.f('ix_git_authorities_user_id'), table_name='git_authorities')
    op.drop_index('idx_user_provider', table_name='git_authorities')
    op.drop_table('git_authorities')
    # ### end Alembic commands ###
