"""add_foreign_key_to_repo_wiki_content_source

Revision ID: 4e2cccbc43ad
Revises: 0cc8e6916a36
Create Date: 2025-11-02 16:23:20.386526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2cccbc43ad'
down_revision: Union[str, Sequence[str], None] = '0cc8e6916a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'fk_repo_wiki_content_sources_content_id',
        'repo_wiki_content_sources',
        'repo_wiki_contents',
        ['content_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_repo_wiki_content_sources_content_id',
        'repo_wiki_content_sources',
        type_='foreignkey'
    )
    # ### end Alembic commands ###
